#include "fsm.h"
#include "defines.h"

struct state_transition
{
    fsm_state_e from;
    button_event_e event; // Event that triggers the transition
    fsm_state_e to;
};

static const struct state_transition state_transitions[] __attribute__((section(".rodata"))) =
{
    {STATE_ROMID, BUTTON_EVENT_SINGLE_PRESS, STATE_BATTERY_V},
    {STATE_ROMID, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_ROMID, BUTTON_EVENT_NONE, STATE_ROMID},
    {STATE_BATTERY_V, BUTTON_EVENT_SINGLE_PRESS, STATE_VEHICLE_SPEED},
    {STATE_BATTERY_V, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_BATTERY_V, BUTTON_EVENT_NONE, STATE_BATTERY_V},
    {STATE_VEHICLE_SPEED, BUTTON_EVENT_SINGLE_PRESS, STATE_ENGINE_SPEED},
    {STATE_VEHICLE_SPEED, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_VEHICLE_SPEED, BUTTON_EVENT_NONE, STATE_VEHICLE_SPEED},
    {STATE_ENGINE_SPEED, BUTTON_EVENT_SINGLE_PRESS, STATE_COOLANT_TEMP},
    {STATE_ENGINE_SPEED, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_ENGINE_SPEED, BUTTON_EVENT_NONE, STATE_ENGINE_SPEED},
    {STATE_COOLANT_TEMP, BUTTON_EVENT_SINGLE_PRESS, STATE_AIRFLOW},
    {STATE_COOLANT_TEMP, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_COOLANT_TEMP, BUTTON_EVENT_NONE, STATE_COOLANT_TEMP},
    {STATE_AIRFLOW, BUTTON_EVENT_SINGLE_PRESS, STATE_THROTTLE},
    {STATE_AIRFLOW, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_AIRFLOW, BUTTON_EVENT_NONE, STATE_AIRFLOW},
    {STATE_THROTTLE, BUTTON_EVENT_SINGLE_PRESS, STATE_THROTTLE_V},
    {STATE_THROTTLE, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_THROTTLE, BUTTON_EVENT_NONE, STATE_THROTTLE},
    {STATE_THROTTLE_V, BUTTON_EVENT_SINGLE_PRESS, STATE_MANIP},
    {STATE_THROTTLE_V, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_THROTTLE_V, BUTTON_EVENT_NONE, STATE_THROTTLE_V},
    {STATE_MANIP, BUTTON_EVENT_SINGLE_PRESS, STATE_BOOST_SOLINOID},
    {STATE_MANIP, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_MANIP, BUTTON_EVENT_NONE, STATE_MANIP},
    {STATE_BOOST_SOLINOID, BUTTON_EVENT_SINGLE_PRESS, STATE_IGNITION_TIMING},
    {STATE_BOOST_SOLINOID, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_BOOST_SOLINOID, BUTTON_EVENT_NONE, STATE_BOOST_SOLINOID},
    {STATE_IGNITION_TIMING, BUTTON_EVENT_SINGLE_PRESS, STATE_LOAD},
    {STATE_IGNITION_TIMING, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_IGNITION_TIMING, BUTTON_EVENT_NONE, STATE_IGNITION_TIMING},
    {STATE_LOAD, BUTTON_EVENT_SINGLE_PRESS, STATE_INJECTOR_PW},
    {STATE_LOAD, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_LOAD, BUTTON_EVENT_NONE, STATE_LOAD},
    {STATE_INJECTOR_PW, BUTTON_EVENT_SINGLE_PRESS, STATE_IAC},
    {STATE_INJECTOR_PW, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_INJECTOR_PW, BUTTON_EVENT_NONE, STATE_INJECTOR_PW},
    {STATE_IAC, BUTTON_EVENT_SINGLE_PRESS, STATE_O2_V},
    {STATE_IAC, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_IAC, BUTTON_EVENT_NONE, STATE_IAC},
    {STATE_O2_V, BUTTON_EVENT_SINGLE_PRESS, STATE_TIMING_CORRECTION},
    {STATE_O2_V, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_O2_V, BUTTON_EVENT_NONE, STATE_O2_V},
    {STATE_TIMING_CORRECTION, BUTTON_EVENT_SINGLE_PRESS, STATE_FUEL_TRIM},
    {STATE_TIMING_CORRECTION, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_TIMING_CORRECTION, BUTTON_EVENT_NONE, STATE_TIMING_CORRECTION},
    {STATE_FUEL_TRIM, BUTTON_EVENT_SINGLE_PRESS, STATE_BAROP},
    {STATE_FUEL_TRIM, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_FUEL_TRIM, BUTTON_EVENT_NONE, STATE_FUEL_TRIM},
    {STATE_BAROP, BUTTON_EVENT_SINGLE_PRESS, STATE_INPUT_SWITCHES},
    {STATE_BAROP, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_BAROP, BUTTON_EVENT_NONE, STATE_BAROP},
    {STATE_INPUT_SWITCHES, BUTTON_EVENT_SINGLE_PRESS, STATE_INOUT_SWITCHES},
    {STATE_INPUT_SWITCHES, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_INPUT_SWITCHES, BUTTON_EVENT_NONE, STATE_INPUT_SWITCHES},
    {STATE_INOUT_SWITCHES, BUTTON_EVENT_SINGLE_PRESS, STATE_ACTIVE_CODE_ONE},
    {STATE_INOUT_SWITCHES, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_INOUT_SWITCHES, BUTTON_EVENT_NONE, STATE_INOUT_SWITCHES},
    {STATE_ACTIVE_CODE_ONE, BUTTON_EVENT_SINGLE_PRESS, STATE_ACTIVE_CODE_TWO},
    {STATE_ACTIVE_CODE_ONE, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_ACTIVE_CODE_ONE, BUTTON_EVENT_NONE, STATE_ACTIVE_CODE_ONE},
    {STATE_ACTIVE_CODE_TWO, BUTTON_EVENT_SINGLE_PRESS, STATE_ACTIVE_CODE_THREE},
    {STATE_ACTIVE_CODE_TWO, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_ACTIVE_CODE_TWO, BUTTON_EVENT_NONE, STATE_ACTIVE_CODE_TWO},
    {STATE_ACTIVE_CODE_THREE, BUTTON_EVENT_SINGLE_PRESS, STATE_STORED_CODE_ONE},
    {STATE_ACTIVE_CODE_THREE, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_ACTIVE_CODE_THREE, BUTTON_EVENT_NONE, STATE_ACTIVE_CODE_THREE},
    {STATE_STORED_CODE_ONE, BUTTON_EVENT_SINGLE_PRESS, STATE_STORED_CODE_TWO},
    {STATE_STORED_CODE_ONE, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_STORED_CODE_ONE, BUTTON_EVENT_NONE, STATE_STORED_CODE_ONE},
    {STATE_STORED_CODE_TWO, BUTTON_EVENT_SINGLE_PRESS, STATE_STORED_CODE_THREE},
    {STATE_STORED_CODE_TWO, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_STORED_CODE_TWO, BUTTON_EVENT_NONE, STATE_STORED_CODE_TWO},
    {STATE_STORED_CODE_THREE, BUTTON_EVENT_SINGLE_PRESS, STATE_ROMID},
    {STATE_STORED_CODE_THREE, BUTTON_EVENT_LONG_PRESS, STATE_ROMID},
    {STATE_STORED_CODE_THREE, BUTTON_EVENT_NONE, STATE_STORED_CODE_THREE}
};

void fsm_process_event(fsm_state_e *state, button_event_e event)
{
    for (int i = 0; i < ARRAY_SIZE(state_transitions); ++i)
    {
        if ((*state == state_transitions[i].from)
             && (event == state_transitions[i].event))
        {
            *state = state_transitions[i].to;
            break;
        }
    }
}
