name: CMake Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test-native:
    name: Run Native Tests via CMake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc make

      - name: Configure CMake
        working-directory: test
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build tests
        working-directory: test/build
        run: make -j$(nproc)

      - name: Run tests with CTest
        working-directory: test/build
        run: ctest --output-on-failure